# Sora OS - Feral GameMode yapılandırması
# Oyun başladığında CPU/GPU optimizasyonları otomatik uygulanır
[general]
desiredgov=performance
defaultgov=schedutil
reaper_freq=5
inhibit_screensaver=1
softrealtime=auto
rename_sched=1

[gpu]
apply_gpu_optimisations=accept-responsibility
nv_powermizer_mode=1
